language: node_js
sudo: false
node_js:
- '6'
after_success: "./script/push"
services:
- docker
cache:
  directories:
  - node_modules
notifications:
  email: false
env:
  global:
  - secure: aSX4rTNcoxxUOT6QogZEHXHs2rAwtGr/ys/QwebV0JY3UO8Q7+WeKNoTddOmc3NCLU1+3x30oy22Fb/hfGoZzpsnyhPDsAcVpC/r867vTiPBMpG+CHfaD360/rLE6VhSNfQEAzJKEqdrefUnl4uqsFox3nwa1A81cQThho2QCoaUnGAUwbGa5FCPUltK/uzfeW2vGr/9Ed6MN4N3BHTT8zWOkvngLCfTZqH8lW4P5sLFRsY4SX3c+mp42gt6Dn5vOsLk/dSGq7pqg54it0t2qtBw6AuAk+Er37vlFjhRof6fFc6/QpUQwoJAV0M4V9tzrGp50PIrC4/yjnlizXC3jllFyZAxoecedP88e7s9KsfRqtIAHSpBSG1AMOaaAZolsUqHTjiiSoxFRfSJn2K+V4p5x6Xc3ibmBfN8beKYE8oZpfk25Rveju1gbZN1N65+fclxztGL5s6/OZXA5mxhB/Rp9/H26D9Js41+EXn9F9j8fHmRsnF0zqNJnwg+8mOpBxulkxF16ZF3YC5SJ7wrQ+qD+Iws60FV1QKdNWT2sH7C6J9COBST3PJdisEUYC0K92jDgrS+7EFrF2m/Vj7b+3dHn8Mf9FaOCBWNm+MGQWeWPZz0nY5OCYuu+ojfyNaHbUtVRP1b4zoCli8PIb3kYnMkw3Eu1DhY9OhhHKLzeiw=
  - secure: K5EYLgTwPDXJuKWVUxm/SicvdK2vwnZ3/mzRrq0rM3bVgVe0E4ruLnc/uLcWplFljAUAP5AbEx73x9UyH+WPgePR/vWvja05dCWUyLYX/bLwktzj1Fnm6PTrngnRrFy5b+RCbcI8Rsl0P/2rhc5Ot3QURFfUtoE0aV/8Y+SaLCD5TUbBNH+OBOF8qtGfAlK4mPOC3K0vhvIVQ9WZQY2jmJSA802uTNTERdHR+76B2+5uLI34q0vbTPGz5qZy9qm/KbXO9UqNmUckqXsTf26BOWT5qchK7m0i0E46QAAwpdJ8nc+2SJC/v7YXAiCERH3BGUcsJ97+HhrTT7ympvWGUHiWS6d0bKbk0/tihdOLHzCRpnr4kt6iCZU3UGRCPFX+jAFrUwp7nbP33LKHygyjflRPMMbJAnyacUDhTOvDqt++zF1d4vXn2F902r52kbGDDSG5aLnTbdFgQza5KrdHGf/eqAly6ewlNBi/TdEQvR1zTOjv6Su0WtbsDKw+VG1g3SdUWjVLIKDQGhfAs7wN46Ag/WBwap0NbhxKm8hUby1RlSCKwR1WiX6p7GrRhkzE2sBOios3+UvYwgOBafDb37qGdA9gPsDQ+BTYex82lEEVvC6dbayne/gQTkbH/wJWDFr6tdJDoKPIGlrtx1Rn347r2alJ9S6uaswGkR93shI=
